package cat.copernic.m03uf06review.pojos;
// Generated Dec 3, 2020 9:07:20 PM by Hibernate Tools 4.3.1


//import cat.copernic.m03uf06review.hibernate_relational.Departamento;
import java.util.Date;
//import javax.persistence.ManyToOne;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {

    /*@ManyToOne
    private Departamento departamento;*/

     private Integer id;
     private int edad;
     private double salario;
     private boolean horasExtra;
     private String iniciales;
     private String puestoDeTrabajo;
     private Date diaEntrada;

    public Empresa() {
    }

    public Empresa(Integer id, int edad, double salario, boolean horasExtra, String iniciales, String puestoDeTrabajo, Date diaEntrada) {
       this.id = id;
       this.edad = edad;
       this.salario = salario;
       this.horasExtra = horasExtra;
       this.iniciales = iniciales;
       this.puestoDeTrabajo = puestoDeTrabajo;
       this.diaEntrada = diaEntrada;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }
    public boolean isHorasExtra() {
        return this.horasExtra;
    }
    
    public void setHorasExtra(boolean horasExtra) {
        this.horasExtra = horasExtra;
    }
    public String getIniciales() {
        return this.iniciales;
    }
    
    public void setIniciales(String iniciales) {
        this.iniciales = iniciales;
    }
    public String getPuestoDeTrabajo() {
        return this.puestoDeTrabajo;
    }
    
    public void setPuestoDeTrabajo(String puestoDeTrabajo) {
        this.puestoDeTrabajo = puestoDeTrabajo;
    }
    public Date getDiaEntrada() {
        return this.diaEntrada;
    }
    
    public void setDiaEntrada(Date diaEntrada) {
        this.diaEntrada = diaEntrada;
    }




}


